[Interface]
PrivateKey = 0Bv1kdl6MZBrV/OAyoUqB13SSSA6PETdKUyDiy0LUE0=
Address = 10.66.66.3/24
DNS = 1.1.1.1

[Peer]
PublicKey = nu3Ps/MfwfhVsfYRJTJP5wfGXF3NgOOz1H+N/ZFv22Y=
Endpoint = 1234567ui:51820
AllowedIPs = 10.66.66.0/24
PersistentKeepalive = 25