[Interface]
PrivateKey = MPzw3q/xkzAS7mcb7hUNmlwkIIqA/VNs6v+D7j9nwGE=
Address = 10.66.66.4/24
DNS = 1.1.1.1

[Peer]
PublicKey = +ig9iEU9rr8AuPfobZN1YhThx2PKE6JgKkxg3P9ByRs=
Endpoint = 117.72.84.199:51820
AllowedIPs = 10.66.66.0/24
PersistentKeepalive = 25