[Interface]
PrivateKey = iFm25fDUK2dcptw6yF7WRVDZ8SZYJqKaXS8rMcwWQUU=
Address = 10.66.66.3/24
DNS = 1.1.1.1

[Peer]
PublicKey = +ig9iEU9rr8AuPfobZN1YhThx2PKE6JgKkxg3P9ByRs=
Endpoint = 117.72.84.199:51820
AllowedIPs = 10.66.66.0/24
PersistentKeepalive = 25