[Interface]
PrivateKey = iBkFy1HhMRYOlDIEo+Klf78mr8pTB32o1Nod0DyYhV0=
Address = 10.66.66.1/24
ListenPort = 51820
[Peer]
# 54321
PublicKey = BsSHD0ygiV/w45nmf/I5Vth7s5AESb2sZePzq2RcyFc=
AllowedIPs = 10.66.66.3/32